export const HEADER_HEIGHT = "HEADER_HEIGHT";
export const FOOTER_HEIGHT = "FOOTER_HEIGHT";

export const REGISTRATION_FETCH = "REGISTRATION_FETCH";
export const LOGIN_FETCH = "LOGIN_FETCH";
export const LOGOUT_FETCH = "LOGOUT_FETCH";

export const LOGIN_STATE = "LOGIN_STATE";
export const LOGOUT_STATE = "LOGOUT_STATE";

export const ASK_YOURSELF = "ASK_YOURSELF";
export const ASK_USER = "ASK_USER";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const DELETE_QUESTIONS = "DELETE_QUESTIONS";
export const GET_QUESTION = "GET_QUESTION";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const GET_NEWSFEED = "GET_NEWSFEED";
export const GET_YOUR_ANSWERS = "GET_YOUR_ANSWERS";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const GET_USER_ANSWERS = "GET_USER_ANSWERS";
export const GET_MY_PROFILE_INFO = "GET_MY_PROFILE_INFO";
export const FOLLOW_USER = "FOLLOW_USER";